### ISSUE TITLE
Crafting Calaculator did not save my settings

### ISSUE THREAD

**Issue by Fizzbin10** [yamamushi/dumap#109]
I entered my talents into the crafting calc, entered a name and saved. Next login the save was gone and all the data I entered has gone with it. The profile was saved as 'Fizzbin'.

Regards
Phil

**Comment by Macroft** [comment]
Did you get a pop up or anything saying settings were old?
Did you clear cookies/website data in between?
Or did everything just vanish?

**Comment by Fizzbin10** [comment]
Yes, I do remember getting a popup with a message to the effect that my settings were old but to be honest I had no idea what actions to take at the time, I'm now asumming that the two are connected. No cookies have been cleared. I entered all my skills and saved them as my username (Fizzbin) but the next day there were no profiles to load. Running Firefox (latest version).
Please advise me what top do to resolve this please.
