### ISSUE TITLE
Missing Uncommon Antenna XS

### ISSUE THREAD

**Issue by ECO-ExPLiCiT** [yamamushi/dumap#110]

**Comment by MitoG** [comment]
Can confirm, the recipe is not shown in the crafting calculator yet it is present in the [recipes,json](https://github.com/yamamushi/dumap/blob/dev/data/recipes.json#L2572)

![image](https://user-images.githubusercontent.com/6368249/96159563-140c1c80-0f15-11eb-89bc-7a0942f1e3f1.png)
