### ISSUE TITLE
Missing honeycomb recipes

### ISSUE THREAD

**Issue by MitoG** [yamamushi/dumap#78]
While the basic recipes for the Honeycomb Refiner M are present (Iron, Aluminum, etc.) the more "complex" ones are missing, for example "Plastic bright yellow".

**Comment by Allen-Tainia** [comment]
Plastic honeycomb is a product honeycomb. look for it under Consumables > Materials > Honeycomb Materials > Product Honeycomb

**Comment by Allen-Tainia** [comment]
Plastic honeycomb is a product honeycomb. look for it under Consumables > Materials > Honeycomb Materials > Product Honeycomb
