### ISSUE TITLE
Crafting/Feature/Machine Requirement

### ISSUE THREAD

**Issue by Macroft** [yamamushi/dumap#81]
It would be nice to know what machines are required for each part. perhaps an icon or just (MW,E,S,R,As/m/l)

Additionally it would be nice to have a total of how many of each machine would be necessary to fully parallelize production. perhaps under the ore requirement box.

**Comment by Allen-Tainia** [comment]
- Look at the detailed info to see what machine are available for each item
- There's so many ways to construct a fully automated production line. In fact for certain items, there's additional factors that come into play (link limits, line topology, catalysts, transfer unit overhead). It all depends on how you design it.

**Comment by Macroft** [comment]
- really the first part was what i was thinking would be most useful, when something pops up on the list i don't have to think about where to get it.. but you are right the detail view does have the information.
- yeah, was more looking for a quick '26 metalwork parts are involved and 13 electronics parts, and 2 3d printed parts... really basic. Those of us that get to the point of link restrictions don't expect anyone to figure that out for us, but your tool does 95% of the work just by tallying production times, was just thinking it would be nice to save the counting :P
