### ISSUE TITLE
Crafting/Feature/Inventory Sort

### ISSUE THREAD

**Issue by Macroft** [yamamushi/dumap#82]
It would be nice to have the option to automatically sort by pipeline stage
Ore>pure>product>inter>complex>...
And sub-sorted by machine

Also it would be handy to have items not vanish when a 0 is put in

**Comment by Allen-Tainia** [comment]
I think it should be easy enough to put a divider of some kind between the items. Not sure what you mean by items vanishing when a 0 is put in?

**Comment by Macroft** [comment]
the step for reproducing:

1. hit checkbox on queue to move it to inventory
2. set inventory count to 0
3. hit checkbox on something else
